const countries = [
    "Bangladesh",
    "Mayotte",
    "Venezuela",
    "Luxembourg",
    "Sweden",
    "Dominican Republic",
    "Ireland",
    "Cambodia",
    "Singapore",
    "San Marino",
    "Laos",
    "Portugal",
    "Malta",
    "Colombia",
    "Albania",
    "Ukraine",
    "Saudi Arabia",
    "Sao Tome and Principe",
    "Macau",
    "Latvia",
    "North Korea",
    "Algeria",
    "U.S. Virgin Islands",
    "Maldives",
    "Slovakia",
    "Israel",
    "Micronesia, Federated States of",
    "Kenya",
    "Malaysia",
    "Zambia",
    "Kuwait",
    "Bosnia and Herzegovina",
    "Liberia",
    "Benin",
    "Cyprus",
    "Nigeria",
    "Pitcairn Islands",
    "South Georgia And South Sandwich Islands",
    "Tajikistan",
    "Guam",
    "China",
    "New Caledonia",
    "Armenia",
    "Qatar",
    "Gabon",
    "Martinique",
    "Australia",
    "Dominica",
    "Serbia",
    "Côte d’Ivoire",
    "British Virgin Islands",
    "Libya",
    "Reunion",
    "Vanuatu",
    "Wallis and Futuna",
    "United Arab Emirates",
    "Georgia",
    "Belgium",
    "Guernsey",
    "Monaco",
    "Solomon Islands",
    "Montserrat",
    "Thailand",
    "El Salvador",
    "The Gambia",
    "Uruguay",
    "Burma",
    "United Kingdom",
    "Germany",
    "Eritrea",
    "Canada",
    "Barbados",
    "Saint Vincent and the Grenadines",
    "Marshall Islands",
    "Namibia",
    "Cook Islands",
    "Slovenia",
    "Azerbaijan",
    "Greece",
    "Egypt",
    "Afghanistan",
    "Chad",
    "Timor-Leste",
    "Saint Kitts and Nevis",
    "Chile",
    "Norfolk Island",
    "Suriname",
    "South Africa",
    "Peru",
    "Isle of Man",
    "Kazakhstan",
    "Kosovo",
    "Japan",
    "Jamaica",
    "Iraq",
    "New Zealand",
    "Ecuador",
    "Russia",
    "Norway",
    "Pakistan",
    "Brazil",
    "Guatemala",
    "Bolivia",
    "Ethiopia",
    "Panama",
    "South Sudan",
    "Yemen",
    "Tunisia",
    "Sudan",
    "Mali",
    "North Macedonia",
    "Morocco",
    "Christmas Island",
    "Moldova",
    "The Bahamas",
    "Svalbard",
    "Mexico",
    "Curaçao",
    "Guyana",
    "Poland",
    "French Guiana",
    "Lebanon",
    "Turks and Caicos Islands",
    "Czechia",
    "Indonesia",
    "Falkland Islands (Islas Malvinas)",
    "Kiribati",
    "Cameroon",
    "Montenegro",
    "Uganda",
    "Jordan",
    "Papua New Guinea",
    "American Samoa",
    "Sri Lanka",
    "Brunei",
    "Uzbekistan",
    "Finland",
    "Grenada",
    "Cayman Islands",
    "Cuba",
    "Kyrgyzstan",
    "France",
    "Djibouti",
    "Nauru",
    "Syria",
    "Senegal",
    "Ghana",
    "Iceland",
    "Madagascar",
    "Hong Kong",
    "Sierra Leone",
    "Philippines",
    "Tuvalu",
    "Cabo Verde",
    "United States",
    "Guinea",
    "Turkey",
    "Rwanda",
    "Zimbabwe",
    "Comoros",
    "Saint Lucia",
    "Belarus",
    "Congo (Brazzaville)",
    "Netherlands",
    "Lesotho",
    "Paraguay",
    "Mauritius",
    "Angola",
    "Bahrain",
    "Spain",
    "Saint Barthelemy",
    "Congo (Kinshasa)",
    "Saint Pierre and Miquelon",
    "Saint Helena, Ascension, and Tristan da Cunha",
    "Malawi",
    "Burundi",
    "Taiwan",
    "Bhutan",
    "Togo",
    "Niue",
    "Burkina Faso",
    "Faroe Islands",
    "Italy",
    "Oman",
    "Eswatini",
    "Fiji",
    "Bonaire, Sint Eustatius, and Saba",
    "Palau",
    "Anguilla",
    "South Korea",
    "Sint Maarten",
    "Bermuda",
    "Argentina",
    "Liechtenstein",
    "Gaza Strip",
    "Puerto Rico",
    "India",
    "Iran",
    "French Polynesia",
    "Estonia",
    "Vietnam",
    "Central African Republic",
    "Guadeloupe",
    "Denmark",
    "Trinidad and Tobago",
    "Mongolia",
    "Mauritania",
    "Mozambique",
    "Northern Mariana Islands",
    "Seychelles",
    "Switzerland",
    "Hungary",
    "Belize",
    "Honduras",
    "Botswana",
    "Romania",
    "Austria",
    "Guinea-Bissau",
    "West Bank",
    "Niger",
    "Vatican City",
    "Lithuania",
    "Bulgaria",
    "Croatia",
    "Turkmenistan",
    "Aruba",
    "South Georgia and South Sandwich Islands",
    "Nicaragua",
    "Tonga",
    "Nepal",
    "Tanzania",
    "Saint Martin",
    "Greenland",
    "Costa Rica",
    "Jersey",
    "Gibraltar",
    "Haiti",
    "Samoa",
    "Equatorial Guinea",
    "Antigua and Barbuda",
    "Andorra",
    "Somalia"
  ];
  
  export default countries;  