const topCategories = ["fiction",
"religion",
"history",
"juvenile fiction",
"biography & autobiography",
"business & economics",
"computers",
"social science",
"juvenile nonfiction",
"science",
"education",
"cooking",
"sports & recreation",
"family & relationships",
"literary criticism",
"music",
"medical",
"art",
"body, mind & spirit",
"language arts & disciplines",
"health & fitness",
"political science",
"psychology",
"philosophy",
"travel",
"technology & engineering",
"self-help",
"poetry",
"foreign language study",
"crafts & hobbies",
"performing arts",
"reference",
"mathematics",
"comics & graphic novels",
"nature",
"architecture",
"transportation",
"law",
"humor",
"photography",
"american literature",
"antiques & collectibles",
"drama",
"bible",
"pets",
"literary collections",
"young adult fiction",
"games",
"gardening",
"study aids",
"games & activities",
"house & home",
"english language",
"bibles",
"united states",
"true crime",
"design",
"great britain",
"childrens stories",
"detective and mystery stories",
"animals",
"christian life",
"audiobooks",
"african americans",
"world war, 1939-1945",
"english fiction",
"copyright",
"american poetry",
"american fiction",
"science fiction",
"children",
"adventure stories",
"france",
"indians of north america",
"conduct of life",
"england",
"frontier and pioneer life",
"authors, american",
"childrens literature",
"books",
"california",
"cats",
"electronic books",
"china",
"comic books, strips, etc",
"large type books",
"english poetry",
"libraries",
"authors",
"dogs",
"europe",
"families",
"canada",
"science fiction, american",
"jews",
"christianity",
"young adult nonfiction",
"railroads",
"brothers and sisters",
"automobiles",
"germany",
"economics",
"authors, english",
"english literature",
"communism",
"birds",
"africa",
"presidents",
"agriculture",
"bibliography, national",
"business",
"actors",
"artists",
"medicine",
"union catalogs",
"biography",
"american wit and humor",
"chess",
"japan",
"australia",
"fairy tales",
"church history",
"spanish language",
"folklore",
"cooking, american",
"crime",
"fantasy fiction",
"encyclopedias and dictionaries",
"adventure and adventurers",
"india",
"dungeons and dragons (game)",
"christmas stories",
"aeronautics",
"american wit and humor, pictorial",
"americans",
"buddhism",
"motion picture actors and actresses",
"child rearing",
"america",
"horses",
"civilization",
"world war, 1914-1918",
"astrology",
"generals",
"country life",
"characters and characteristics in literature",
"women",
"astronomy",
"greece",
"mormon church",
"authorship",
"english drama",
"friendship",
"detective and mystery stories, american",
"egypt",
"readers",
"american drama",
"baseball",
"apologetics",
"occultism",
"baptists",
"bears",
"firearms",
"alaska",
"audiotapes",
"ireland",
"islam",
"man-woman relationships",
"childrens poetry",
"prayer",
"airplanes",
"curiosities and wonders",
"fiction in english",
"murder",
"childrens libraries",
"chicago (ill.)",
"british",
"government publications",
"short stories",
"fantasy fiction, american",
"composers",
"christian fiction",
"marriage",
"fantasy",
"vietnam war, 1961-1975",
"cookbooks",
"boys",
"rock musicians",
"german language",
"biology",
"fantasy games",
"christmas",
"cookery",
"algebra",
"cancer",
"motion pictures",
"gay men",
"automobile racing",
"ethnology",
"architecture, domestic",
"russia",
"self-actualization (psychology)",
"success",
"domestic fiction",
"literature",
"advertising",
"board books",
"computer networks",
"florida",
"physics",
"chemistry",
"popular literature",
"computer industry",
"spiritual life",
"fishing",
"love",
"ghosts",
"rome",
];


export default topCategories; 